export type ConnectorAuthType = 'apiToken' | 'password';
export type ConnectorProvider = 'proxmox' | 'oci' | 'aws' | 'azure' | 'gcp' | 'github';

export type ProxmoxConnector = {
  id: string;
  provider?: ConnectorProvider;
  name: string;
  host: string;
  port: number;
  realm: string;
  username: string;
  authType: ConnectorAuthType;
  apiTokenId: string;
  tenancyOcid?: string;
  userOcid?: string;
  compartmentOcid?: string;
  awsAccountId?: string;
  awsAccessKeyId?: string;
  azureTenantId?: string;
  azureSubscriptionId?: string;
  azureClientId?: string;
  azureCloud?: 'public' | 'gov' | 'china';
  azureSubscriptionName?: string;
  azureApprovedRegions?: string;
  gcpProjectId?: string;
  gcpProjectName?: string;
  gcpProjectNumber?: string;
  gcpClientEmail?: string;
  gcpOrganizationId?: string;
  gcpBillingAccountId?: string;
  githubUsername?: string;
  region?: string;
  fingerprint?: string;
  tlsVerify: boolean;
  notes: string;
  status: 'ready' | 'verified' | 'error';
  lastVerifiedAt: string | null;
  verificationMessage: string;
  selected: boolean;
  createdAt: string;
  updatedAt: string;
  secretPreview: string;
  secretStored: boolean;
};

export type ConnectorInput = {
  provider?: ConnectorProvider;
  name: string;
  host: string;
  port: number;
  realm: string;
  username: string;
  authType: ConnectorAuthType;
  password: string;
  apiTokenId: string;
  apiTokenSecret: string;
  tenancyOcid?: string;
  userOcid?: string;
  compartmentOcid?: string;
  awsAccountId?: string;
  awsAccessKeyId?: string;
  awsSecretAccessKey?: string;
  awsSessionToken?: string;
  azureTenantId?: string;
  azureSubscriptionId?: string;
  azureClientId?: string;
  azureClientSecret?: string;
  azureCloud?: 'public' | 'gov' | 'china';
  azureApprovedRegions?: string;
  gcpProjectId?: string;
  gcpClientEmail?: string;
  gcpOrganizationId?: string;
  gcpBillingAccountId?: string;
  githubUsername?: string;
  githubToken?: string;
  region?: string;
  fingerprint?: string;
  privateKey?: string;
  privateKeyPassphrase?: string;
  tlsVerify: boolean;
  notes: string;
};
