export type ResourceRecord = {
  id?: string;
  node?: string;
  vmid?: number;
  name?: string;
  type?: string;
  status?: string;
  cpu?: number;
  mem?: number;
  maxmem?: number;
  disk?: number;
  maxdisk?: number;
  storage?: string;
  content?: string;
  disable?: boolean | number;
  uptime?: number;
  template?: number | boolean;
  region?: string;
  resourceGroup?: string;
  compartmentId?: string;
  compartmentName?: string;
  description?: string;
  providerType?: string;
  shape?: string;
  size?: string;
  os?: string;
  availabilityDomain?: string;
  zone?: string;
  faultDomain?: string;
  sizeGb?: number | string;
  diskSizeGb?: number | string;
  osDiskId?: string;
  cidrBlock?: string;
  dnsLabel?: string;
  vcnId?: string;
  vcnName?: string;
  vpcId?: string;
  vpcName?: string;
  projectId?: string;
  routeTableId?: string;
  routingMode?: string;
  priority?: string | number;
  direction?: string;
  routes?: Array<{ destination?: string; target?: string; state?: string; origin?: string }>;
  routeRules?: Array<{ destination?: string; destinationType?: string; networkEntityId?: string; description?: string; routeType?: string }>;
  associations?: Array<{ id?: string; subnetId?: string; gatewayId?: string; main?: boolean; state?: string }>;
  ingressRules?: Array<{ direction?: string; protocol?: string; fromPort?: string; toPort?: string; cidrBlocks?: string[]; sourceGroups?: string[] }>;
  egressRules?: Array<{ direction?: string; protocol?: string; fromPort?: string; toPort?: string; cidrBlocks?: string[]; sourceGroups?: string[] }>;
  securityListIds?: string[];
  subnetId?: string;
  subnetName?: string;
  gatewayType?: string;
  drgId?: string;
  drgName?: string;
  networkDetails?: { id?: string; type?: string };
  peeringStatus?: string;
  peerId?: string;
  peerRegionName?: string;
  rulesCount?: number;
  services?: Array<{ serviceId?: string; serviceName?: string; name?: string }>;
  scope?: string;
  zoneType?: string;
  zoneId?: string;
  zoneName?: string;
  viewId?: string;
  domain?: string;
  rtype?: string;
  rdata?: string;
  ttl?: number | string;
  namespace?: string;
  storageTier?: string;
  publicAccessType?: string;
  publicAccessStatus?: string;
  versioning?: string | boolean;
  objectEventsEnabled?: string | boolean;
  bucketName?: string;
  key?: string;
  sizeBytes?: number | string;
  storageClass?: string;
  etag?: string;
  eTag?: string;
  lastModified?: string;
  contentType?: string;
  updatedAt?: string;
  createdAt?: string;
  resourceType?: string;
  ocpus?: number | string;
  memoryGb?: number | string;
  storageSizeGb?: number | string;
  storageType?: string;
  operationType?: string;
  maxSizeBytes?: number | string;
  attachedVmId?: string;
  attachedVmName?: string;
  ipConfigurationId?: string;
  allowBlobPublicAccess?: string | boolean;
  tier?: string;
  sku?: string;
  state?: string;
  endpoint?: string;
  port?: number | string;
  publiclyAccessible?: string | boolean;
  backupRetentionPeriod?: number | string;
  multiAz?: string | boolean;
  dbSubnetGroup?: string;
  dbInstanceId?: string;
  snapshotId?: string;
  snapshotType?: string;
  imageId?: string;
  sourceVmId?: string;
  sourceVirtualMachineId?: string;
  restorePointCollectionId?: string;
  restorePointCollectionName?: string;
  consistencyMode?: string;
  vpcSecurityGroups?: Array<{ id?: string; status?: string }>;
  privateIp?: string;
  publicIp?: string;
  recommendation?: string;
  impact?: string;
  reason?: string;
  monthlyEstimate?: string;
  estimatedMonthlyCost?: number;
  source?: string;
  dbName?: string;
  dbVersion?: string;
  databaseEdition?: string;
  licenseModel?: string;
  workloadType?: string;
  cpuCoreCount?: number | string;
  dbSystemId?: string;
  dbHomeId?: string;
  dbNodeCount?: number | string;
  hostname?: string;
  accountId?: string;
  engine?: string;
  dnsName?: string;
  scheme?: string;
  instanceId?: string;
  attachedInstanceId?: string;
  volumeId?: string;
  device?: string;
  tags?: Array<{ key?: string; value?: string }> | Record<string, string>;
  labels?: Array<{ key?: string; value?: string }> | Record<string, string>;
  sourceDisk?: string;
  sourceImage?: string;
  rawSummary?: Record<string, string>;
};

export type DashboardData = {
  generatedAt: string;
  summary: {
    clusterHealth: 'healthy' | 'attention';
    totalNodes: number;
    onlineNodes: number;
    totalVMs: number;
    totalVMTemplates: number;
    runningVMs: number;
    stoppedVMs: number;
    containers: number;
    runningContainers: number;
    cpuUsage: number;
    memoryUsage: number;
    storageUsage: number;
  };
  charts: {
    cpu: Array<{ name: string; usage: number }>;
    memory: Array<{ name: string; used: number; total: number; usage: number }>;
    storage: Array<{ name: string; used: number; total: number; usage: number }>;
    status: Array<{ name: string; value: number }>;
  };
  resources: {
    nodes: ResourceRecord[];
    vms: ResourceRecord[];
    vmTemplates: ResourceRecord[];
    containers: ResourceRecord[];
    storage: ResourceRecord[];
    allCompute: ResourceRecord[];
  };
};
